### ISSUE TITLE
short email address not normalizing

### ISSUE THREAD

**Issue by milobob** [dimuska139/go-email-normalizer#3]
BoB.tester@domain.com correctly normalizes to bobtester@domain.com
However
BoB@domain.com normalizes to BoB@domain.com instead of bob@domain.com

**Comment by dimuska139** [comment]
@milobob The first part of the address may be case sensitive (RFC 5336). See [this PR](https://github.com/dimuska139/go-email-normalizer/pull/1)

**Comment by milobob** [comment]
So I'm not as much of an expert as you, I don't know what RFC 5336 is, but google email addresses are not case sensitive and so the go-email-normalizer is not solving the problem of duplicate email addresses on my server from google email addresses. 

I did find a workaround, and that's to do:
n := normalizer.NewNormalizer()
	//email with uppercase case and dots removed to be unique
	emailLowerCasePre := n.Normalize(userEmail)
	emailLowerCase := strings.ToLower(emailLowerCasePre) //normalizer should automatically do this but it doesn't seem to for short email addresses

**Comment by dimuska139** [comment]
@milobob go-email-normalizer has separate rule https://github.com/dimuska139/go-email-normalizer/blob/master/google_rule.go for domains gmail.com, googlemail.com and google.com. This rule converts the first part of email address (before @) to lowercase and cuts it to a plus sign. 

Can you provide you google emails as an example (slightly change them for safety)? Maybe I missed some domain...

**Comment by milobob** [comment]
ohhh I see! I am using @companydomain.com where my companydomain is connected to google workspace! So maybe I need to make a custom rule for the companydomain?

**Comment by dimuska139** [comment]
@milobob you can just add Google rule to you companydomain:
```go
package main

import (
	"fmt"

	normalizer "github.com/dimuska139/go-email-normalizer"
)

func main() {
	n := normalizer.NewNormalizer()
	n.AddRule("companydomain.com", &normalizer.GoogleRule{})
	fmt.Println(n.Normalize("tEst.goOgle@companydomain.com") == n.Normalize("TeStgoOgle+test@companydomain.com")) // true
}
```

**Comment by milobob** [comment]
uh oh... that changes:
Bob@domain.com to  bob@gmail.com

I'll just stick with my ToLower hack!

**Comment by dimuska139** [comment]
@milobob Are you worried about domain changing to gmail.com? There is no way to compare alex@gmail.com and alex@google.com (this is the same email addresses) without it. This library converts email addresses to the normalized form - so domain in result (after normalizing) should not be different.

**Comment by milobob** [comment]
n.AddRule("companydomain.com", &normalizer.GoogleRule{})
fmt.Println(n.Normalize("tEst.goOgle@companydomain.com")  results in tEst.goOgle@gmail.com so it changes the email domain. So I'll stick to the ToLower hack!

**Comment by milobob** [comment]
I don't want an account for bob@mycompanydomain.com to be stored on my server as bob@gmail.com

**Comment by dimuska139** [comment]
@milobob you should use the normalized version of the email address only for internal usage. You should not display it in UI. So you can use something like this users table structure in your database: id (pk), key (normalized email, id from social network etc), registration_type (via email address + password, using facebook etc), email (user's real email). Also You should create composite unique index on fields "key" and "registration_type". When the user tries to create an account on site (using email and password authentication), you should normalize his email address and check the existence in the database by fields key and registration_type (for ex: _SELECT * FROM users WHERE key='<normalized email address>' AND registration_type='email+password'_). Thus, the "email" field (in users table) is only needed to be displayed in the user interface. It is not used in the duplicate checking logic. So the email domain does not matter, because the user will not see it.
